# https://taskfile.dev

version: '3'

vars:
  EXTENSION_UUID: hours-counter@ekyoz.github.io
  EXTENSION_DIR: '{{.USER_WORKING_DIR}}'
  DIST_DIR: '{{.EXTENSION_DIR}}/dist'
  INSTALL_DIR: '{{.HOME}}/.local/share/gnome-shell/extensions/{{.EXTENSION_UUID}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  schemas:
    desc: Compile GSettings schemas
    cmds:
      - glib-compile-schemas {{.EXTENSION_DIR}}/schemas/
    sources:
      - schemas/*.xml
    generates:
      - schemas/gschemas.compiled

  build:
    desc: Build extension zip package for distribution
    deps: [schemas]
    cmds:
      - mkdir -p {{.DIST_DIR}}
      - |
        cd {{.EXTENSION_DIR}} && zip -r {{.DIST_DIR}}/{{.EXTENSION_UUID}}.zip \
          extension.js \
          prefs.js \
          metadata.json \
          LICENSE \
          README.md \
          CHANGELOG.md \
          schemas/
      - echo "✅ Package created at {{.DIST_DIR}}/{{.EXTENSION_UUID}}.zip"
    sources:
      - extension.js
      - prefs.js
      - metadata.json
      - schemas/*.xml
    generates:
      - dist/{{.EXTENSION_UUID}}.zip

  install:
    desc: Install extension locally
    deps: [schemas]
    cmds:
      - mkdir -p {{.INSTALL_DIR}}
      - cp -r {{.EXTENSION_DIR}}/extension.js {{.INSTALL_DIR}}/
      - cp -r {{.EXTENSION_DIR}}/prefs.js {{.INSTALL_DIR}}/
      - cp -r {{.EXTENSION_DIR}}/metadata.json {{.INSTALL_DIR}}/
      - cp -r {{.EXTENSION_DIR}}/schemas {{.INSTALL_DIR}}/
      - cp -r {{.EXTENSION_DIR}}/LICENSE {{.INSTALL_DIR}}/
      - echo "✅ Extension installed. Restart GNOME Shell to apply changes."
      - echo "   X11=> Press Alt+F2, type 'r', press Enter"
      - echo "   Wayland=> Log out and log back in"

  uninstall:
    desc: Uninstall extension
    cmds:
      - rm -rf {{.INSTALL_DIR}}
      - echo "✅ Extension uninstalled"

  enable:
    desc: Enable the extension
    cmds:
      - gnome-extensions enable {{.EXTENSION_UUID}}
      - echo "✅ Extension enabled"

  disable:
    desc: Disable the extension
    cmds:
      - gnome-extensions disable {{.EXTENSION_UUID}}
      - echo "✅ Extension disabled"

  restart:
    desc: Restart GNOME Shell (X11 only)
    cmds:
      - busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting…")'
      - echo "✅ GNOME Shell restarting..."

  logs:
    desc: Show extension logs
    cmds:
      - journalctl -f -o cat /usr/bin/gnome-shell | grep -i hours-counter

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.DIST_DIR}}
      - rm -f schemas/gschemas.compiled
      - echo "✅ Cleaned build artifacts"

  bump:
    desc: "Bump version (usage: task bump -- patch|minor|major)"
    cmds:
      - |
        VERSION_FILE="{{.EXTENSION_DIR}}/metadata.json"
        CURRENT_VERSION=$(grep '"version-name"' "$VERSION_FILE" | sed 's/.*"\([0-9]*\.[0-9]*\.[0-9]*\)".*/\1/')
        
        if [ -z "$CURRENT_VERSION" ]; then
          CURRENT_VERSION="1.0.0"
        fi
        
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
        
        case "{{.CLI_ARGS}}" in
          major)
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            ;;
          minor)
            MINOR=$((MINOR + 1))
            PATCH=0
            ;;
          patch|"")
            PATCH=$((PATCH + 1))
            ;;
          *)
            echo "❌ Invalid version type: {{.CLI_ARGS}}"
            echo "   Usage: task bump -- [patch|minor|major]"
            exit 1
            ;;
        esac
        
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        
        # Get current integer version
        CURRENT_INT=$(grep '"version"' "$VERSION_FILE" | head -1 | sed 's/[^0-9]*//g')
        NEW_INT=$((CURRENT_INT + 1))
        
        # Update metadata.json
        sed -i "s/\"version\": $CURRENT_INT/\"version\": $NEW_INT/" "$VERSION_FILE"
        sed -i "s/\"version-name\": \"$CURRENT_VERSION\"/\"version-name\": \"$NEW_VERSION\"/" "$VERSION_FILE"
        
        # Update README badge
        sed -i "s/Version-[0-9]*\.[0-9]*\.[0-9]*/Version-$NEW_VERSION/" "{{.EXTENSION_DIR}}/README.md"
        
        echo "✅ Version bumped: $CURRENT_VERSION → $NEW_VERSION (build $NEW_INT)"
        echo ""
        echo "📝 Don't forget to:"
        echo "   1. Commit: git commit -am 'Bump version to $NEW_VERSION'"
        echo "   2. Tag: git tag -a v$NEW_VERSION -m 'Version $NEW_VERSION'"
        echo "   3. Push: git push && git push --tags"

  release:
    desc: Create a release (bump + build + commit + tag)
    cmds:
      - task: bump
        vars:
          CLI_ARGS: '{{.CLI_ARGS}}'
      - task: build
      - |
        VERSION=$(grep '"version-name"' metadata.json | sed 's/.*"\([0-9]*\.[0-9]*\.[0-9]*\)".*/\1/')
        
        echo ""
        echo "📝 Creating commit and tag..."
        
        git add -A
        git commit -m "Release v$VERSION"
        git tag -a "v$VERSION" -m "Release v$VERSION"
        
        echo ""
        echo "✅ Release v$VERSION created!"
        echo "📦 Package ready at dist/{{.EXTENSION_UUID}}.zip"
        echo ""
        echo "📋 Next steps:"
        echo "   1. git push && git push --tags"
        echo "   2. Upload dist/{{.EXTENSION_UUID}}.zip to extensions.gnome.org"

  validate:
    desc: Validate extension for publishing
    cmds:
      - |
        echo "🔍 Validating extension..."
        ERRORS=0
        
        # Check required files
        for file in extension.js metadata.json; do
          if [ ! -f "{{.EXTENSION_DIR}}/$file" ]; then
            echo "❌ Missing required file: $file"
            ERRORS=$((ERRORS + 1))
          else
            echo "✅ Found: $file"
          fi
        done
        
        # Check metadata.json
        if [ -f "{{.EXTENSION_DIR}}/metadata.json" ]; then
          for field in uuid name description shell-version version; do
            if ! grep -q "\"$field\"" "{{.EXTENSION_DIR}}/metadata.json"; then
              echo "❌ Missing field in metadata.json: $field"
              ERRORS=$((ERRORS + 1))
            fi
          done
        fi
        
        # Check schemas
        if [ -d "{{.EXTENSION_DIR}}/schemas" ]; then
          if ls {{.EXTENSION_DIR}}/schemas/*.xml 1> /dev/null 2>&1; then
            echo "✅ Schema XML files found"
          else
            echo "⚠️  No schema XML files found in schemas/"
          fi
        fi
        
        if [ $ERRORS -eq 0 ]; then
          echo ""
          echo "✅ Extension validation passed!"
        else
          echo ""
          echo "❌ Validation failed with $ERRORS error(s)"
          exit 1
        fi
